name: Fly Deploy
on: [push]
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        run: |
          'debug: false
        httpport: 80
        grpcport: 5555
          oauth2:
            type: "github"
            admin: "lyj0309"
            clientid: "b02ab61a75edd1b98f11"
            clientsecret: ${{ secrets.CLIENT_SECRET }}
          site:
            brand: "fakev-status"
            cookiename: "nezha-dashboard"
            theme: "default"
        ' > config.yaml
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only


